import { ArrowLeft, FileText } from "lucide-react";
import { Link } from "wouter";

const sections = [
  {
    heading: "1. Acceptance of Terms",
    body: [
      "By accessing or using Custody Atlas (\"Service,\" \"we,\" \"us,\" or \"our\") at custodyatlas.com, you agree to be bound by these Terms of Service (\"Terms\"). If you do not agree to these Terms, do not use the Service.",
      "These Terms constitute a legally binding agreement between you and Andre Oliver, the owner and operator of Custody Atlas.",
    ],
  },
  {
    heading: "2. Not Legal Advice — Important Disclaimer",
    body: [
      "CUSTODY ATLAS IS NOT A LAW FIRM AND DOES NOT PROVIDE LEGAL ADVICE.",
      "The information, analysis, summaries, and responses generated by Custody Atlas are for general informational purposes only and do not constitute legal advice, legal representation, or the practice of law. No attorney-client relationship is formed by your use of this Service.",
    ],
    bullets: [
      "Nothing in the Service should be relied upon as a substitute for competent legal advice from a licensed attorney in your jurisdiction.",
      "Custody law varies significantly by state, county, and individual circumstances. Information provided may not apply to your specific situation.",
      "You should always consult a licensed family law attorney before making any legal decisions related to custody, child support, visitation, or any related matter.",
      "AI-generated responses may contain errors, omissions, or outdated information.",
    ],
    closing:
      "USE THIS SERVICE AT YOUR OWN RISK. WE ARE NOT RESPONSIBLE FOR ANY DECISIONS YOU MAKE BASED ON INFORMATION PROVIDED BY THE SERVICE.",
  },
  {
    heading: "3. Eligibility",
    body: [
      "You must be at least 18 years old to use this Service. By using the Service, you represent that you are 18 or older and have the legal capacity to enter into these Terms.",
    ],
  },
  {
    heading: "4. Your Account",
    body: [
      "You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You agree to notify us immediately of any unauthorized use of your account.",
    ],
  },
  {
    heading: "5. Acceptable Use",
    body: ["You agree not to use the Service to:"],
    bullets: [
      "Violate any applicable law or regulation",
      "Harass, threaten, or harm any individual",
      "Upload false, misleading, or fraudulent information",
      "Attempt to gain unauthorized access to the Service or its systems",
      "Use the Service for any commercial purpose without our written consent",
      "Scrape, copy, or redistribute any content from the Service",
      "Impersonate any person or entity",
    ],
  },
  {
    heading: "6. Document Upload and Privacy",
    body: [
      "When you upload documents to the Service, you represent that you have the legal right to share those documents and that doing so does not violate any court order, confidentiality agreement, or applicable law.",
      "Documents you upload are processed by AI systems to provide analysis and responses. You retain ownership of your documents. We do not sell your documents or their contents to third parties.",
    ],
  },
  {
    heading: "7. Subscription and Billing",
    body: [
      "Free tier accounts are subject to lifetime usage limits. Paid Pro subscriptions are billed through Stripe and include monthly usage allowances. Subscription fees are non-refundable except as required by applicable law. We reserve the right to change pricing with 30 days' notice.",
    ],
  },
  {
    heading: "8. Intellectual Property",
    body: [
      "All content, features, and functionality of the Service — including but not limited to software, text, graphics, logos, and AI models — are owned by Andre Oliver and are protected by intellectual property laws. You may not copy, reproduce, or distribute any part of the Service without our express written permission.",
    ],
  },
  {
    heading: "9. Limitation of Liability",
    body: [
      "TO THE MAXIMUM EXTENT PERMITTED BY LAW, CUSTODY ATLAS AND ITS OWNER SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF DATA, LOSS OF PROFITS, OR ANY OTHER LOSSES ARISING FROM YOUR USE OF THE SERVICE, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.",
      "OUR TOTAL LIABILITY TO YOU FOR ANY CLAIMS ARISING FROM OR RELATED TO THE SERVICE SHALL NOT EXCEED THE AMOUNT YOU PAID TO US IN THE 12 MONTHS PRECEDING THE CLAIM.",
    ],
  },
  {
    heading: "10. Indemnification",
    body: [
      "You agree to indemnify and hold harmless Custody Atlas and its owner from any claims, damages, losses, or expenses (including attorney's fees) arising from your use of the Service, your violation of these Terms, or your violation of any rights of a third party.",
    ],
  },
  {
    heading: "11. Termination",
    body: [
      "We reserve the right to suspend or terminate your account at any time for violation of these Terms or for any other reason at our discretion. You may delete your account at any time.",
    ],
  },
  {
    heading: "12. Changes to Terms",
    body: [
      "We may modify these Terms at any time. We will notify registered users of material changes by email or by posting a notice in the Service. Continued use of the Service after changes constitutes acceptance of the modified Terms.",
    ],
  },
  {
    heading: "13. Governing Law",
    body: [
      "These Terms are governed by the laws of the State of Georgia, without regard to its conflict of law principles. Any disputes arising from these Terms shall be resolved in the courts located in Georgia.",
    ],
  },
  {
    heading: "14. Contact",
    body: [
      "For questions about these Terms, contact us at: support@custodyatlas.com",
      "Phone: (404) 692-2006",
    ],
  },
];

export default function TermsOfServicePage() {
  return (
    <div className="bg-slate-950 text-slate-100">
      <div className="max-w-3xl mx-auto px-4 py-12 sm:px-6">
        <Link href="/" className="inline-flex items-center gap-2 text-sm text-slate-400 transition-colors hover:text-slate-100">
          <ArrowLeft className="h-4 w-4" />
          Back
        </Link>

        <div className="mt-8 rounded-3xl border border-white/10 bg-slate-900/70 p-6 shadow-2xl shadow-slate-950/30 sm:p-10">
          <div className="flex items-start gap-4">
            <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-500/10 text-blue-300">
              <FileText className="h-6 w-6" />
            </div>
            <div>
              <p className="text-sm uppercase tracking-[0.2em] text-blue-300/80">Custody Atlas</p>
              <h1 className="mt-2 text-3xl font-semibold tracking-tight">Terms of Service</h1>
              <p className="mt-2 text-sm text-slate-400">Last updated: April 17, 2026</p>
            </div>
          </div>

          <div className="mt-8 rounded-2xl border border-amber-500/20 bg-amber-500/10 px-5 py-4 text-sm leading-7 text-amber-100">
            Custody Atlas provides general information only and does not provide legal advice.
            Always consult a licensed attorney before making legal decisions.
          </div>

          <div className="mt-10 space-y-8">
            {sections.map((section) => (
              <section key={section.heading} className="space-y-4">
                <h2 className="text-xl font-semibold text-slate-50">{section.heading}</h2>
                {section.body.map((paragraph) => (
                  <p key={paragraph} className="text-base leading-8 text-slate-300">
                    {paragraph}
                  </p>
                ))}
                {section.bullets ? (
                  <ul className="space-y-3 pl-5 text-base leading-8 text-slate-300 marker:text-blue-300 list-disc">
                    {section.bullets.map((bullet) => (
                      <li key={bullet}>{bullet}</li>
                    ))}
                  </ul>
                ) : null}
                {section.closing ? (
                  <p className="text-base font-semibold leading-8 text-amber-100">{section.closing}</p>
                ) : null}
              </section>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
